# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
    - name: 'Install package'
      run: npm install
    - name: 'Compile TypeScript files'
      run: npm run compile

  esm-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
    - name: 'Test ESM'
      run: npm run test:esm
      
  cjs-test:
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
    - name: 'Test CJS'
      run: npm run test:cjs
